k37y/openshift-network-playground

ignition/00-core.bu, ignition/00-core.ign
- Add Console credentials
- Add CLI credentials
- Modify success message
Fixes: #29
=> refactor: Improve credentials display

manifest.yaml
=> feat: Add packages

ignition/00-core.bu, ignition/00-core.ign
=> feat: Add `~/.zshenv`

manifest.yaml, manifests/aarch64-drop-qcom-dtb-files.yaml, manifests/fallback-hostname.yaml, manifests/fedora-coreos.yaml, manifests/ostree-autoprune.yaml, manifests/shared-el9.yaml, overlay.d/06el9
- Add files
- Modify files
- Update submodule
- Bump FCOS version
=> ci: new release v0.2.0

ignition/00-core.bu
- Correct ENV to ignore reverse-proxy container
Fixes #67
=> bug: Correct CONTAINERS Makefile ENV

.github/workflows/build-customize-release.yaml, Makefile, hack/changelog.sh
- Add changelog & release-tag Make target
- Modify GH action
- Add hack/changelog.sh script to generate changelog
Fixes #77
=> ci: Add changelog

Makefile
- Add release
- Add tag
- Add check-version
=> ci: Add Make targets

.github/workflows/build-release-test.yaml
=> ci: Add GitHub action

.github/workflows/build-release-test.yaml
- Wrap changelog content in YAML block scalar
=> refactor: User block scalar

.github/workflows/build-customize-artifact.yaml
- Show changelog
- Build ISO
- Upload ISO
=> ci: Build artifact

.github/workflows/build-customize-artifact.yaml
- Use action/upload-artifact@v3
=> ci: Correct upload artifact

.github/workflows/build-customize-release.yaml, Makefile
- Correct Make target named tag
- Correct release CI steps
=> ci: Improve release CI

README.md
=> doc: Correct ISO URL

README.md
- Licence
- Downloads
- Artifact
- OpenShift lab
=> doc: Add shields

README.md
=> doc: Add JetBrain logo

ignition/00-core.bu, ignition/00-core.ign
- Replace it with cloud-utils-growpart
=> bug: Correct Fedora disk grow package

Makefile
- Add -f for git commands
Fixes: #104
=> ci: Add force option for Make taget tag

ignition/00-core.bu, ignition/00-core.ign
- Add After: network-online.target
Fixes: #94
=> bug: Fix VM break at startup

ignition/00-core.bu
- Improve image name parsing
- Add NETWORK option for rhcos.sh
=> Improve rhcos.sh and vm.sh

README.md
- Add bullet points for prerequisites
=> doc: Modify README
